### ISSUE TITLE
brakujące pliki

### ISSUE THREAD

**Issue by ramilami** [vfjpl/oldmargonem#2]
brakuje paru plików
[https://iv.pl/images/64587c8c796db234c9fc937e92151aba.png](url)

**Comment by vfjpl** [comment]
@ramilami wymagane zależności to SFML, TGUI i POCO.

Linux:
https://aur.archlinux.org/packages/tgui/
a reszta w repozytorium

Na windowsie trzeba poszukać na stronach projektów:
https://www.sfml-dev.org/
https://tgui.eu/
https://pocoproject.org/

Nie testowałem czy na windowsie się kompiluje.

**Comment by ramilami** [comment]
Jakiego edytora używałeś? Visual studio czy co?

**Comment by vfjpl** [comment]
@ramilami CodeBlocks

**Comment by ramilami** [comment]
po zainstalowaniu bibliotek i próby kompilacji kodu wyskakują  mi błędy
https://iv.pl/images/a8ccfd352d4b66be412b8e7138074b2c.png

**Comment by vfjpl** [comment]
@ramilami funkcja Network::login() przyjmuje dwa parametry, "login" i "hasło". Wpisz w 65 linijce pliku engine.cpp   Network::login("twójlogin", "twojehasło");

Obecnie jest to zrobione w taki sposób, gdyż były ważniejsze rzeczy do implementacji.

**Comment by TomakiPL3** [comment]
Można jakiś króciutki poradnik jak to odpalić? Z góry dziękuje i pozdrawiam :)

**Comment by ramilami** [comment]
jak ogarne wszystko to zrobię ci poradnik

**Comment by TomakiPL3** [comment]
Ooo to super dziękuje z góry ;)

**Comment by ramilami** [comment]
zwraca mi błąd że nie mogę wywołać funkcji bez obiektu,
uczyłem się c++ rok temu ale nie doszedłem do takiego momentu żeby zrozumieć to.

ss: https://iv.pl/images/5914b986825faa68f489a1157f340302.png

można jakiś kontakt z tobą (discord, gg, fb, ig)? bo tak to będziemy robić to nie wiadomo ile,
albo zrób poradnik jak to zrobić.

dzięki w ogóle za pomoc @vfjpl  ;)

**Comment by vfjpl** [comment]
@ramilami Niezbyt precyzyjnie napisałem. Chodzi oczywiście o:
network.login("login", "hasło");

tak jak było wcześniej tylko z dodanym loginem i hasłem.

**Comment by ramilami** [comment]
dalej jest błąd

> obj\Release\engine.o:engine.cpp:(.text$_ZNK4Poco3Net4Impl21IPv6SocketAddressImpl4hostEv[__ZNK4Poco3Net4Impl21IPv6SocketAddressImpl4hostEv]+0x20)||undefined reference to `Poco::Net::IPAddress::IPAddress(void const*, int, unsigned int)'|


> obj\Release\engine.o:engine.cpp:(.text$_ZN4Poco3Net4Impl21IPv6SocketAddressImplD1Ev[__ZN4Poco3Net4Impl21IPv6SocketAddressImplD1Ev]+0x7)||undefined reference to `Poco::Net::Impl::SocketAddressImpl::~SocketAddressImpl()'|

**Comment by vfjpl** [comment]
@ramilami nie linkujesz biblioteki POCO

**Comment by ramilami** [comment]
teraz to nie rozumiem.

**Comment by vfjpl** [comment]
@ramilami https://stackoverflow.com/questions/5862757/how-do-i-link-to-a-library-with-codeblocks

**Comment by ramilami** [comment]
a o to ci chodzi, ale co mam tam wpisać?

**Comment by vfjpl** [comment]
@ramilami Generalnie mamy 3 fazy:
1. Preprocesor
potrzebne pliki nagłówkowe .hpp
czyli wszystko co co jest w #include

2. kompilacja
potrzebne pliki .cpp
powstają pliki .o

3. linkowanie
łączenie wszystkich plików .o i bibliotek w jeden plik wykonywalny

u ciebie jest problem z 3 fazą bo kompilator nie dostał plików biblioteki

jak te biblioteki zainstalowałeś?

**Comment by vfjpl** [comment]
@ramilami tu masz tutorial do codeblocksa https://www.sfml-dev.org/tutorials/2.5/start-cb.php

może to Ci pomoże

**Comment by ramilami** [comment]
Project>Build options>search directories

i do compailer wszystkie pliki include
ss: https://iv.pl/images/e588c738b2e432a52803dac0b458f97e.png
a do linker wszystkie pliki lib
ss: https://iv.pl/images/3f33df4a87a355cb1f28113ec255d104.png

i do linker settings dodałem sfml
ss : https://iv.pl/images/e0600c078174fe1f1447cfb7ba47d2ee.png

**Comment by vfjpl** [comment]
@ramilami korzystałeś z pliku .cbp który jest w projekcie?

tutaj pełna lista do linker settings
		PocoNet
		PocoFoundation
		tgui
		sfml-network
		sfml-graphics
		sfml-window
		sfml-system

**Comment by ramilami** [comment]
jak dodam ten folder bin do linker settings to pisze mi odmowa dostępu @vfjpl

**Comment by ramilami** [comment]
o dzięki :)

**Comment by ramilami** [comment]
dalej coś nie tak

> obj\Release\engine.o:engine.cpp:(.text$_ZNK4Poco3Net4Impl21IPv6SocketAddressImpl4hostEv[__ZNK4Poco3Net4Impl21IPv6SocketAddressImpl4hostEv]+0x20)||undefined reference to `Poco::Net::IPAddress::IPAddress(void const*, int, unsigned int)'|

> obj\Release\engine.o:engine.cpp:(.text$_ZN4Poco3Net4Impl21IPv6SocketAddressImplD1Ev[__ZN4Poco3Net4Impl21IPv6SocketAddressImplD1Ev]+0x7)||undefined reference to `Poco::Net::Impl::SocketAddressImpl::~SocketAddressImpl()'|

**Comment by ramilami** [comment]
![linker](https://user-images.githubusercontent.com/34812517/67152124-f344c300-f2d0-11e9-922c-42ae45345e2f.PNG)

**Comment by vfjpl** [comment]
@ramilami skąd pobrałeś bibliotekę POCO?

**Comment by ramilami** [comment]
![download](https://user-images.githubusercontent.com/34812517/67152156-559dc380-f2d1-11e9-988d-eb9b8cf83757.PNG)

**Comment by ramilami** [comment]
@vfjpl z oficjalnej strony, pobrałem do visual c++ bo do code blocka nie było.

**Comment by vfjpl** [comment]
from https://www.sfml-dev.org/download/sfml/2.5.1/
 "The compiler versions have to match 100%!"

Co zapewne tyczy się to też POCO.

**Comment by vfjpl** [comment]
@ramilami 
Generalnie wszystkie biblioteki i kod muszą być skompilowane tym samym kompilatorem. albo MiniGW albo TDM albo Visual C++

Możesz albo spróbować skompilować POCO samemu albo spróbować cały projekt skompilować pod visual studio

**Comment by ramilami** [comment]
spoko, jutro spróbuje.
masz discorda albo gg?

**Comment by ramilami** [comment]
![błąd](https://user-images.githubusercontent.com/34812517/67159598-de0a7b80-f346-11e9-9846-1ab01f35f9bd.PNG)
 coś nie tak jest

**Comment by vfjpl** [comment]
@ramilami 
Pierwsze dwa błędy są powiązane.
Pierwszy błąd jest spowodowany tym, że kompilator Visual c++ nie ma pliku sys/time.h
Drugi jest spowodowany tym, że nie znalazło funkcji gettimeofday która jest w pliku sys/time.h

Możesz albo spróbować przerobić tą funkcję by korzystała z innej funkcji. Lub zwracaj w tej funkcji po prostu jakieś 9 losowych cyfr w jako tekst bo nie jestem pewien czy w ogóle oldmargonem korzysta z tego.

Trzeci błąd. consexpr oznacza, że wynik funkcji(to co zwróci) może zostać obliczony podczas samej kompilacji zamiast podczas tego gdy program działa jeśli wynik nie zależy od niczego co wprowadzi użytkownik. Co jest potrzebne bo case w switchu potrzebuje stałej wartości. Stąd cała reszta błędów. Wydaje mi się, że kompilator nie wie co robi funkcja strlen() i dlatego nie może obliczyć jej wyniku. Sprawdz czy std::strlen(str) zamiast strlen(str) coś zmieni. Ale nie jestem pewien. Dziwny błąd…

**Comment by vfjpl** [comment]
@ramilami spróbuj też nowszych wersji standardu c++ np c++17

**Comment by vfjpl** [comment]
@ramilami Zmieniłem definicję str2int by nie korzystała z strlen(). Teraz powinna się kompilować pod kompilatorem z Visual c++

**Comment by ramilami** [comment]
okej zobaczę
